pub use syn::token::{For, In, Where};

custom_keyword!(index);
custom_keyword!(integer);
custom_keyword!(int);
custom_keyword!(float);
custom_keyword!(boolean);
custom_keyword!(bool);
custom_keyword!(string);
custom_keyword!(str);
custom_keyword!(text);
custom_keyword!(binary);
custom_keyword!(bin);
custom_keyword!(unique);
custom_keyword!(uni);
custom_keyword!(duplicate);
custom_keyword!(dup);
custom_keyword!(find);
custom_keyword!(order);
custom_keyword!(by);
custom_keyword!(asc);
custom_keyword!(desc);
custom_keyword!(insert);
custom_keyword!(into);
custom_keyword!(update);
custom_keyword!(modify);
custom_keyword!(remove);
custom_keyword!(from);
